export class Customer {
    constructor(
        public CustomerID: Number,
public CompanyID: Number,
public BranchID: Number,
public LineID: Number,
public StateID: Number,
public DistrictID: Number,
public TalukID: Number,
public AreaID: Number,
public SubAreaID: Number,
public CustName: string,
public Initial: string,
public FatherName: string,
public MotherName: string,
public Gender: string,
public MaritalStatus: string,
public SpouseName: string,
public ResidentType: string,
public CommAddress: string,
public NativAddress: string,
public OccupationType: string,
public OccupationDetail: string,
public CustContact1: string,
public CustContact2: string,
public CustAadhar: string,
public CustPanCard: string,
public CustFamilyCard: string,
public CustVoterId: string,
public CustDriveLnce: string,
public GuarantorName: string,
public Relationship: string,
public GContactNum1: string,
public GContactNum2: string,
public GAddress: string,
public GPermAddress: string,
public GResidentType: string,
public GAadhar: string,
public GPanCard: string,
public GFamilyCard: string,
public GVoterId: string,
public GDriveLnce: string,
public ReferenceName: string,
public CustStatus: string,
public Remarks: string,
public Hint1:string,
public Hint2:string
    )
    {

    }
}