export class Loan{
    constructor(
        public CustomerID: Number,
        public CompanyID: Number,
        public BranchID: Number,
        public LineID: Number,
        public StateID: Number,
        public DistrictID: Number,
        public TalukID: Number,
        public AreaID: Number,
        public SubAreaID: Number,
        public CustName: string,
        public Initial: string,
        public FatherName: string,
        public MotherName: string,
        public Gender: string,
        public MaritalStatus: string,
        public SpouseName: string,
        public ResidentType: string,
        public CommAddress: string,
        public NativAddress: string,
        public OccupationType: string,
        public OccupationDetail: string,
        public CustContact1: string,
        public CustContact2: string,
        public CustAadhar: string,
        public CustPanCard: string,
        public CustFamilyCard: string,
        public CustVoterId: string,
        public CustDriveLnce: string,
        public GuarantorName: string,
        public Relationship: string,
        public GContactNum1: string,
        public GContactNum2: string,
        public GAddress: string,
        public GPermAddress: string,
        public GResidentType: string,
        public GAadhar: string,
        public GPanCard: string,
        public GFamilyCard: string,
        public GVoterId: string,
        public GDriveLnce: string,
        public ReferenceName: string,
        public CustStatus: string,
        public CustRemarks: string,
        public Hint1:string,
        public Hint2:string,
        public  LoanID: Number ,
        public  LoanCatID: Number ,
        public  LoanNo: Number ,
        public LoanDate: Date ,
        public  LoanMethod:string  ,
        public Agent_ShowroomID:  Number,
        public  Label1Value: string ,
        public  Label2Value: string ,
        public  Label3Value: string ,
        public  CollectionMethod:  string,
        public  AgentResponsible: Boolean ,
        public  PaymentByBank: Boolean ,
        public  SecurityType: Boolean ,
        public  MortgageDoc: Boolean ,
        public  OriginalDoc: Boolean ,
        public  Patta: Boolean ,
        public  RCBook:  Boolean,
        public  NoofCheque: string ,
        public  LoanAmt: Number ,
        public  DueType: Number ,
        public  IntRate: Number ,
        public  IntType: string ,
        public  LastIntCalcDt: Date ,
        public  IntBal: Number ,
        public  TotLoanAmt: Number ,
        public  DocCharge: Number ,
        public  DocChargeReceived:string  ,
        public  IncentiveCalcBy: string ,
        public  IncentiveRatio: Number ,
        public  IncentiveAmt: Number ,
        public  IncentiveType: string ,
        public  SplIncentiveAmt: Number ,
        public  Scheme: string ,
        public  SchemeCalcAmt: Number ,
        public  SchemeAmt: Number ,
        public  SchemeAmtReceived: string ,
        public  Instalments: Number ,
        public  InterestAmt:Number  ,
        public  TotAmount: Number ,
        public  FirstDueDt:  Date,
        public  LastDueDt: Date  ,
        public  InstalmentAmt: Number ,
        public  NetAmt: Number ,
        public  DueBal: Number ,
        public  LastPenCalcDate: Date ,
        public  PenaltyBal: Number ,
        public  LoanBal: Number ,
        public  RoundedOff: Number ,
        public  LoanStatus: string ,
        public  Remarks:  string,
        public  LoanSubStatus: string ,
        public  RepaymentGrade:  string,
        public  CustomerAttitude:  string,
        public  NOCRemarks:  string
    )
    {

    }
}