export interface IIRequest
{
   SNO:Number
   CustomerID:Number
   LoanNo:Number
   LineName:string
    AreaName:string
    CustomerName:string
   Initial:string
  LoanDate:string
    LoanCategory:string
    AgentName:string
    TotAmount:Number
    TotLoanAmt:Number
    InterestAmt:Number
    NetAmt:Number
   CreatedBy:string
   PaymentByBank:boolean
}