export interface IDueList
{
    SNo	:string
LINE	:string
AREA	:string
CustomerID	:string
CustName	:string
Initial	:string
FatherName	:string
MotherName	:string
SpouseName	:string
CommAddress	:string
CustContact1	:string
CustContact2	:string
GuarantorName	:string
Relationship	:string
GResidentType	:string
GAddress	:string
GContactNum1	:string
GContactNum2	:string
LoanCatID	:string
LoanNo	:string
LoanDate	:string
Agent_ShowroomID	:string
Label1Value	:string
Label2Value	:string
Label3Value	:string
CollectionMethod	:string
AgentResponsible	:string
PaymentByBank	:string
NoofCheque	:string
LoanAmt	:string
DueType	:string
IntRate	:string
TotLoanAmt	:string
DocCharge	:string
Scheme	:string
Instalments	:string
InterestAmt	:string
TotAmount	:string
FirstDueDt	:string
LastDueDt	:string
InstalmentAmt	:string
Remarks	:string
LoanSubStatus	:string
CreatedBy	:string
TotalReceived 	:string
OLoanBal 	:string
ODueBal 	:string
OPenBal 	:string
OIntBal 	:string
DueAmt 	:string
PenAmt 	:string
IntAmt 	:string
DueReceipt 	:string
PenReceipt 	:string
IntReceipt 	:string
CLoanBal 	:string
CDueBal 	:string
CPenBal 	:string
CIntBal 	:string
PendingDueAmt 	:string
PendingDue 	:string
OD 	:string
ReceivableAmt 	:string
CollectDay 	:string
}